name: publish to nuget
on:
  push:
    branches:
      - dev 
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: build
        run: ./build.ps1
        shell: pwsh
      - name: publish nuget
        run: ./publish.nuget.ps1
        env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}        
        shell: pwsh
